// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "github.com/kuromii5/chat-bot-auth-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockJWTManager is an autogenerated mock type for the JWTManager type
type MockJWTManager struct {
	mock.Mock
}

type MockJWTManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTManager) EXPECT() *MockJWTManager_Expecter {
	return &MockJWTManager_Expecter{mock: &_m.Mock}
}

// GenerateAccess provides a mock function with given fields: userID, role
func (_m *MockJWTManager) GenerateAccess(userID uuid.UUID, role domain.Role) (string, error) {
	ret := _m.Called(userID, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccess")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, domain.Role) (string, error)); ok {
		return rf(userID, role)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, domain.Role) string); ok {
		r0 = rf(userID, role)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, domain.Role) error); ok {
		r1 = rf(userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTManager_GenerateAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccess'
type MockJWTManager_GenerateAccess_Call struct {
	*mock.Call
}

// GenerateAccess is a helper method to define mock.On call
//   - userID uuid.UUID
//   - role domain.Role
func (_e *MockJWTManager_Expecter) GenerateAccess(userID interface{}, role interface{}) *MockJWTManager_GenerateAccess_Call {
	return &MockJWTManager_GenerateAccess_Call{Call: _e.mock.On("GenerateAccess", userID, role)}
}

func (_c *MockJWTManager_GenerateAccess_Call) Run(run func(userID uuid.UUID, role domain.Role)) *MockJWTManager_GenerateAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(domain.Role))
	})
	return _c
}

func (_c *MockJWTManager_GenerateAccess_Call) Return(_a0 string, _a1 error) *MockJWTManager_GenerateAccess_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTManager_GenerateAccess_Call) RunAndReturn(run func(uuid.UUID, domain.Role) (string, error)) *MockJWTManager_GenerateAccess_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokenExpiry provides a mock function with no fields
func (_m *MockJWTManager) RefreshTokenExpiry() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokenExpiry")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockJWTManager_RefreshTokenExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokenExpiry'
type MockJWTManager_RefreshTokenExpiry_Call struct {
	*mock.Call
}

// RefreshTokenExpiry is a helper method to define mock.On call
func (_e *MockJWTManager_Expecter) RefreshTokenExpiry() *MockJWTManager_RefreshTokenExpiry_Call {
	return &MockJWTManager_RefreshTokenExpiry_Call{Call: _e.mock.On("RefreshTokenExpiry")}
}

func (_c *MockJWTManager_RefreshTokenExpiry_Call) Run(run func()) *MockJWTManager_RefreshTokenExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJWTManager_RefreshTokenExpiry_Call) Return(_a0 time.Duration) *MockJWTManager_RefreshTokenExpiry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockJWTManager_RefreshTokenExpiry_Call) RunAndReturn(run func() time.Duration) *MockJWTManager_RefreshTokenExpiry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWTManager creates a new instance of MockJWTManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTManager {
	mock := &MockJWTManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
