// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kuromii5/chat-bot-auth-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenRepo is an autogenerated mock type for the TokenRepo type
type MockTokenRepo struct {
	mock.Mock
}

type MockTokenRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepo) EXPECT() *MockTokenRepo_Expecter {
	return &MockTokenRepo_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function with given fields: ctx, token
func (_m *MockTokenRepo) CreateToken(ctx context.Context, token *domain.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepo_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type MockTokenRepo_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.RefreshToken
func (_e *MockTokenRepo_Expecter) CreateToken(ctx interface{}, token interface{}) *MockTokenRepo_CreateToken_Call {
	return &MockTokenRepo_CreateToken_Call{Call: _e.mock.On("CreateToken", ctx, token)}
}

func (_c *MockTokenRepo_CreateToken_Call) Run(run func(ctx context.Context, token *domain.RefreshToken)) *MockTokenRepo_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RefreshToken))
	})
	return _c
}

func (_c *MockTokenRepo_CreateToken_Call) Return(_a0 error) *MockTokenRepo_CreateToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepo_CreateToken_Call) RunAndReturn(run func(context.Context, *domain.RefreshToken) error) *MockTokenRepo_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenRepo) GetToken(ctx context.Context, tokenHash string) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepo_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockTokenRepo_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepo_Expecter) GetToken(ctx interface{}, tokenHash interface{}) *MockTokenRepo_GetToken_Call {
	return &MockTokenRepo_GetToken_Call{Call: _e.mock.On("GetToken", ctx, tokenHash)}
}

func (_c *MockTokenRepo_GetToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepo_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepo_GetToken_Call) Return(_a0 *domain.RefreshToken, _a1 error) *MockTokenRepo_GetToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepo_GetToken_Call) RunAndReturn(run func(context.Context, string) (*domain.RefreshToken, error)) *MockTokenRepo_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenRepo) RevokeToken(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepo_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockTokenRepo_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepo_Expecter) RevokeToken(ctx interface{}, tokenHash interface{}) *MockTokenRepo_RevokeToken_Call {
	return &MockTokenRepo_RevokeToken_Call{Call: _e.mock.On("RevokeToken", ctx, tokenHash)}
}

func (_c *MockTokenRepo_RevokeToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepo_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepo_RevokeToken_Call) Return(_a0 error) *MockTokenRepo_RevokeToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepo_RevokeToken_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenRepo_RevokeToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepo creates a new instance of MockTokenRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepo {
	mock := &MockTokenRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
