// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	session "github.com/kuromii5/chat-bot-auth-service/internal/service/session"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, req
func (_m *MockService) Login(ctx context.Context, req session.LoginRequest) (*session.LoginResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *session.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, session.LoginRequest) (*session.LoginResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, session.LoginRequest) *session.LoginResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, session.LoginRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req session.LoginRequest
func (_e *MockService_Expecter) Login(ctx interface{}, req interface{}) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", ctx, req)}
}

func (_c *MockService_Login_Call) Run(run func(ctx context.Context, req session.LoginRequest)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(session.LoginRequest))
	})
	return _c
}

func (_c *MockService_Login_Call) Return(_a0 *session.LoginResponse, _a1 error) *MockService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(context.Context, session.LoginRequest) (*session.LoginResponse, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *MockService) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockService_Expecter) Logout(ctx interface{}, refreshToken interface{}) *MockService_Logout_Call {
	return &MockService_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *MockService_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *MockService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_Logout_Call) Return(_a0 error) *MockService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, req
func (_m *MockService) Refresh(ctx context.Context, req session.RefreshRequest) (*session.RefreshResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *session.RefreshResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, session.RefreshRequest) (*session.RefreshResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, session.RefreshRequest) *session.RefreshResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.RefreshResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, session.RefreshRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - req session.RefreshRequest
func (_e *MockService_Expecter) Refresh(ctx interface{}, req interface{}) *MockService_Refresh_Call {
	return &MockService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, req)}
}

func (_c *MockService_Refresh_Call) Run(run func(ctx context.Context, req session.RefreshRequest)) *MockService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(session.RefreshRequest))
	})
	return _c
}

func (_c *MockService_Refresh_Call) Return(_a0 *session.RefreshResponse, _a1 error) *MockService_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Refresh_Call) RunAndReturn(run func(context.Context, session.RefreshRequest) (*session.RefreshResponse, error)) *MockService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
