// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	user "github.com/kuromii5/chat-bot-auth-service/internal/service/user"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Register provides a mock function with given fields: ctx, req
func (_m *MockService) Register(ctx context.Context, req user.RegisterRequest) (*user.RegisterResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *user.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.RegisterRequest) (*user.RegisterResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.RegisterRequest) *user.RegisterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req user.RegisterRequest
func (_e *MockService_Expecter) Register(ctx interface{}, req interface{}) *MockService_Register_Call {
	return &MockService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockService_Register_Call) Run(run func(ctx context.Context, req user.RegisterRequest)) *MockService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.RegisterRequest))
	})
	return _c
}

func (_c *MockService_Register_Call) Return(_a0 *user.RegisterResponse, _a1 error) *MockService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Register_Call) RunAndReturn(run func(context.Context, user.RegisterRequest) (*user.RegisterResponse, error)) *MockService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePreferences provides a mock function with given fields: ctx, userID, emailEnabled
func (_m *MockService) UpdatePreferences(ctx context.Context, userID uuid.UUID, emailEnabled bool) error {
	ret := _m.Called(ctx, userID, emailEnabled)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePreferences")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, userID, emailEnabled)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UpdatePreferences_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePreferences'
type MockService_UpdatePreferences_Call struct {
	*mock.Call
}

// UpdatePreferences is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - emailEnabled bool
func (_e *MockService_Expecter) UpdatePreferences(ctx interface{}, userID interface{}, emailEnabled interface{}) *MockService_UpdatePreferences_Call {
	return &MockService_UpdatePreferences_Call{Call: _e.mock.On("UpdatePreferences", ctx, userID, emailEnabled)}
}

func (_c *MockService_UpdatePreferences_Call) Run(run func(ctx context.Context, userID uuid.UUID, emailEnabled bool)) *MockService_UpdatePreferences_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockService_UpdatePreferences_Call) Return(_a0 error) *MockService_UpdatePreferences_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UpdatePreferences_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *MockService_UpdatePreferences_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
